#!/usr/bin/env bash
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=tools.sh
source "$here/tools.sh"

prefix=/opt/nightshift/stack-wow
bin=/usr/local/bin
export WOW_HOME=/var/cache/nightshift/wow
export WOW_CACHE="$WOW_HOME/cache"
export WOW_LUACHECKRC="$WOW_HOME/luacheckrc"

if [ "$(id -u)" -ne 0 ]; then
  echo "install.sh must run as root" >&2
  exit 1
fi

case "$(uname -m)" in
  x86_64 | amd64) arch=amd64 ;;
  aarch64 | arm64) arch=arm64 ;;
  *)
    echo "unsupported architecture $(uname -m)" >&2
    exit 1
    ;;
esac

sha() {
  local var="${1}_SHA256_${arch^^}"
  printf '%s' "${!var}"
}


tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

fetch() {
  local url="$1" sum="$2" out="$tmp/$3"
  curl -fsSL --proto '=https' --proto-redir '=https' --retry 3 -o "$out" "$url"
  if ! echo "$sum  $out" | sha256sum -c --quiet -; then
    echo "checksum mismatch for $url" >&2
    exit 1
  fi
  printf '%s' "$out"
}

ensure_packages() {
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y --no-install-recommends ca-certificates curl tar gzip git python3 \
    "lua5.1=$LUA_DEB_VERSION" "lua-check=$LUACHECK_DEB_VERSION"
  # Do not depend on the base image's update-alternatives choice (which may be Lua 5.4+).
  ln -sfn /usr/bin/lua5.1 "$bin/lua"
  rm -rf /var/lib/apt/lists/*
}

# The commit id pins the content; sparse paths keep the image small.
checkout() {
  local repo="$1" commit="$2" dir="$3"
  shift 3
  rm -rf "$dir"
  git init -q "$dir"
  git -C "$dir" remote add origin "$repo"
  git -C "$dir" sparse-checkout set --no-cone "$@"
  git -C "$dir" fetch -q --depth 1 --filter=blob:none origin "$commit"
  git -C "$dir" -c advice.detachedHead=false checkout -q FETCH_HEAD
  if [ "$(git -C "$dir" rev-parse HEAD)" != "$commit" ]; then
    echo "$repo checked out $(git -C "$dir" rev-parse HEAD), expected $commit" >&2
    exit 1
  fi
  rm -rf "$dir/.git"
}

install_lua_language_server() {
  local archive dir="$prefix/lua-language-server"
  archive="$(fetch "$(LUA_LANGUAGE_SERVER_URL)" "$(sha LUA_LANGUAGE_SERVER)" luals.tgz)"
  rm -rf "$dir"
  mkdir -p "$dir"
  tar -xzf "$archive" -C "$dir"
  chmod -R a+rX "$dir"
  cat >"$bin/lua-language-server" <<EOF
#!/usr/bin/env bash
set -euo pipefail
state="\${TMPDIR:-/tmp}/lua-language-server-\$(id -u)"
exec "$dir/bin/lua-language-server" --logpath="\$state/log" --metapath="\$state/meta" "\$@"
EOF
  chmod 0755 "$bin/lua-language-server"
}

install_sources() {
  mkdir -p "$WOW_HOME"
  checkout https://github.com/Ketho/vscode-wow-api "$WOW_API_COMMIT" "$WOW_HOME/wow-api" /Annotations/
  checkout https://github.com/Gethe/wow-ui-source "$WOW_UI_SOURCE_COMMIT" "$WOW_HOME/wow-ui-source" /Interface/ /version.txt
  checkout https://github.com/Ketho/BlizzardInterfaceResources "$WOW_RESOURCES_COMMIT" "$WOW_HOME/resources" \
    /Resources/FrameXML.lua /Resources/Frames.lua /Resources/GlobalAPI.lua /Resources/GlobalStrings/enUS.lua
  install -m 0644 "$here/tools.sh" "$WOW_HOME/pins.sh"
  test -d "$WOW_HOME/wow-api/Annotations"
  test -d "$WOW_HOME/wow-ui-source/Interface/AddOns/Blizzard_APIDocumentationGenerated"
}

write_luarc() {
  cat >"$WOW_HOME/luarc.json" <<JSON
{
  "runtime.version": "Lua 5.1",
  "runtime.builtin": {
    "basic": "disable",
    "debug": "disable",
    "io": "disable",
    "math": "disable",
    "os": "disable",
    "package": "disable",
    "string": "disable",
    "table": "disable",
    "utf8": "disable"
  },
  "workspace.library": ["$WOW_HOME/wow-api/Annotations"],
  "workspace.checkThirdParty": false,
  "workspace.ignoreDir": ["Libs", "libs", ".git"]
}
JSON
}

resource_globals() {
  local dir="$WOW_HOME/resources/Resources" f
  for f in "$dir/FrameXML.lua" "$dir/Frames.lua" "$dir/GlobalAPI.lua"; do
    sed -n -E 's/^[[:space:]]*"([A-Za-z_][A-Za-z0-9_]*)[".].*/\1/p' "$f"
  done
  sed -n -E 's/^_G\["([A-Za-z_][A-Za-z0-9_]*)"\].*/\1/p; s/^([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=.*/\1/p' \
    "$dir/GlobalStrings/enUS.lua"
}

# Every top-level name in the annotations and Blizzard's generated global lists becomes a read-only global.
write_luacheckrc() {
  {
    printf -- '-- generated by the nightshift wow stack; a .luacheckrc in the repository wins\n'
    printf 'std = "none"\nmax_line_length = false\nread_globals = {\n'
    {
      find "$WOW_HOME/wow-api/Annotations" -type f -name '*.lua' -print0 |
        xargs -0 sed -n -E 's/^(function[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*)[[:space:].(=].*/\2/p'
      resource_globals
    } | grep -v -E '^(local|return|end|if|for|while|do|repeat|else|elseif|then|and|or|not|nil|true|false)$' |
      sort -u | sed 's/.*/  "&",/'
    printf '}\n'
  } >"$WOW_LUACHECKRC"
}

install_tools() {
  install -D -m 0755 "$here/wow-tools.py" "$prefix/bin/wow-tools.py"
  for tool in wow-api wow-check; do ln -sfn "$prefix/bin/wow-tools.py" "$bin/$tool"; done
}

warm_caches() {
  local addon="$tmp/Warm"
  mkdir -p "$WOW_CACHE" "$addon"
  printf '## Interface: %s\nWarm.lua\n' "${WOW_INTERFACE:-120100}" >"$addon/Warm.toc"
  printf 'print("warm")\n' >"$addon/Warm.lua"
  "$bin/wow-api" C_PetJournal.GetPetInfoTableByPetID >/dev/null
  "$bin/wow-check" --fast "$addon" >/dev/null
  # Both indexes are baked into the image. Workers only need read access.
  chmod 0755 "$WOW_CACHE"
  chmod -R a+rX "$WOW_HOME"
}

ensure_packages
install_lua_language_server
install_sources
write_luarc
write_luacheckrc
install_tools
warm_caches
